-- by: iElden

INSERT INTO Types(Type, Kind) VALUES
	('MPH_VICTORY_ECONOMY', 'KIND_VICTORY'),
	('MPH_BUILDING_ECONOMY_VICTORY_MONUMENT', 'KIND_BUILDING');

INSERT INTO Victories(VictoryType, Name, Description, Blurb, RequirementSetId, CriticalPercentage) VALUES
	('MPH_VICTORY_ECONOMY', 'LOC_MPH_VICTORY_ECONOMY_NAME','LOC_MPH_VICTORY_ECONOMY_DESCRIPTION','LOC_MPH_VICTORY_ECONOMY_TEXT','REQUIREMENTS_MPH_VICTORY_ECONOMY', 120);
	
INSERT INTO Buildings(BuildingType, Name, Description, Cost, PrereqDistrict, MustPurchase, PurchaseYield, AdvisorType) VALUES
	('MPH_BUILDING_ECONOMY_VICTORY_MONUMENT', 'LOC_MPH_BUILDING_ECONOMY_VICTORY_MONUMENT_NAME', 'LOC_MPH_BUILDING_ECONOMY_VICTORY_MONUMENT_DESCRIPTION', 20000, 'DISTRICT_CITY_CENTER', 1, 'YIELD_GOLD', 'ADVISOR_GENERIC');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
	('REQUIREMENTS_MPH_VICTORY_ECONOMY', 'REQUIREMENTSET_TEST_ALL'),
	('REQUIREMENTS_MPH_VICTORY_ECONOMY_PER_TEAM', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
	('REQUIREMENTS_MPH_VICTORY_ECONOMY', 'MPH_VICTORY_ECONOMY_REQUIREMENTS_MET'),
	('REQUIREMENTS_MPH_VICTORY_ECONOMY_PER_TEAM', 'MPH_ECONOMY_VICTORY_FLAG');

INSERT INTO Requirements(RequirementId, RequirementType, Persistent) VALUES
	('MPH_VICTORY_ECONOMY_REQUIREMENTS_MET', 'REQUIREMENT_COLLECTION_ANY_MET', 0),
	('MPH_ECONOMY_VICTORY_FLAG', 'REQUIREMENT_PLAYER_HAS_BUILDING',1);
	
INSERT INTO RequirementArguments(RequirementId, Name,Value) VALUES
	('MPH_VICTORY_ECONOMY_REQUIREMENTS_MET', 'CollectionType','COLLECTION_TEAM_PLAYERS'),
	('MPH_VICTORY_ECONOMY_REQUIREMENTS_MET', 'RequirementSetId','REQUIREMENTS_MPH_VICTORY_ECONOMY_PER_TEAM'),
	('MPH_ECONOMY_VICTORY_FLAG', 'BuildingType','MPH_BUILDING_ECONOMY_VICTORY_MONUMENT');

INSERT INTO RequirementStrings(RequirementId, Context,Text) VALUES
	('MPH_VICTORY_ECONOMY_REQUIREMENTS_MET', 'VictoryProgress','LOC_MPH_VICTORY_ECONOMY_PROGRESS'),
	('MPH_ECONOMY_VICTORY_FLAG', 'VictoryProgress','LOC_MPH_VICTORY_ECONOMY_PROGRESS');

-- remove free building from torre de belem.
DElETE FROM BuildingModifiers WHERE ModifierId='TORREDEBELEM_CHEAPEST_BUILDING';